---
- name: Automation Create vlan
  hosts: networks_nexus
  gather_facts: true
  vars:
    vlan_name: "vlan11"
    vlan_number: "11"

  tasks:
    - name: Get timestamp
      ansible.builtin.command: "date +%Y-%m-%d_%H-%M-%S"
      delegate_to: localhost
      register: timestamp
    - name: Debug timestamp
      ansible.builtin.debug:
        msg: "{{ timestamp.stdout }}"


    - name: Backup Nexus config
      cisco.nxos.nxos_config:
        # backup: yes
        backup: true
        backup_options:
          filename: "backup_config_nexus_{{timestamp.stdout}}"
          # dir_path: "/home/satlusr/playbook/network/backup/nexus/{{inventory_hostname}}"
          dir_path: "."

    - name: Check vlan before create
      cisco.nxos.nxos_facts:
        gather_subset: all
      register: check_vlan
    
    - name: debug check vlan
      ansible.builtin.debug:
        msg: "{{ check_vlan }}"

    - name: Create vlan{{vlan_number}}
      cisco.nxos.nxos_vlans:
        config:
          - vlan_id: "{{vlan_number}}"
            name: "{{vlan_name}}"
        state: merged
      when: vlan_number not in check_vlan.ansible_facts.ansible_net_vlan_list