---
- name: Configure VLAN on Cisco Nexus
  hosts: nxos
  connection: local
  gather_facts: false

  tasks:
    - name: Include vlan vars
      include_vars:
        file: "{{ vlan_file }}.yml"

    - name: Query NXOS
      cisco.nxos.nxos_facts:
        gather_subset: all
      register: response

    - name: VLANs found on NXOS Device
      ansible.builtin.debug:
        msg: "{{ response.ansible_facts.ansible_net_vlan_list }}"

    - name: Build array of vlan ids from vlan var file
      ansible.builtin.set_fact:
        vlans_check: "{{ vlans | map(attribute='id') | list }}"

    - name: VLANs Required
      ansible.builtin.debug:
        msg: "{{ vlans_check }}"
    - name: Check for VLAN Existance
      ansible.builtin.debug:
        msg: "vlanId {{ item }} has been found"
      with_items: "{{ response.ansible_facts.ansible_net_vlan_list }}"
      loop_control:
        label: "{{ item }}"
      when: item in vlans_check

    - name: Create vlan
      cisco.nxos.nxos_vlans:
        config:
        - vlan_id: "{{ item.id }}"
          name: "{{ item.name }}"
        state: merged
      with_items: "{{ vlans }}"

